basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: 一个简单的 Swagger 示例
  title: 示例 API 文档
  version: "1.0"
paths:
  /ping:
    get:
      description: 返回 pong
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 测试接口
      tags:
      - 示例
swagger: "2.0"
